### PR TITLE
Material info

### PR DESCRIPTION
**Pull request by tasnmb**
Added navbar

### CODE REVIEW

**Review by recyclinginnova — CHANGES_REQUESTED** [review]
Hi Tas,

I like the changes you've made, however, there are some changes I would like you to consider.

Firstly, I think you should move the screen widgets to their own separate files. I understand that you might have done that to quickly check if they were working or not, but still, they should be on their own files as they are likely to grow in the future. 

Secondly, it would probably be better if the navigation bar were to be its own widget as a wrapper widget around the `NagivationBar` widget. It would also be a good setup for when you do eventually implement the fix that you have noted in line 16.

Lastly, on line 18, I don't think `index` is a great name for a class member variable. Perhaps `selectedScreen` or `currentScreen` would be better?

If you have any objections to the suggestions I've made, please, do let me know and I will be happy to reconsider.

Thanks!

**Comment by tasnmb** [comment]
Hey,

I'm fine with creating separate files for the screens and will commit that shortly,

However I'm confused by the request to wrap the Navigation Bar in its own widget. The navbar I used is part of the Scaffold class. If I move the navbar to its own widget and run, then the app bar will not show up. 

as shown by here:
image

Therefore I will not make that change for now.

Also, the variable name `index` was chosen as it stores a numerical value, which is the index of the current screen needed in the `screens` list. It is also based off the `selectedIndex` variable in the `NavigationBar` class. 

I am happy to change it, however I feel that `index` or `currentIndex` is a more suitable name.

**Review by recyclinginnova — CHANGES_REQUESTED** [review]
As per my last review, extract the navigation bar into its own widget

Thanks!

**Comment by tasnmb** [comment]
Please

**Review by recyclinginnova — APPROVED** [review]

**Pull request merged**
